### ISSUE TITLE
Implement refresh every minute

### ISSUE THREAD

**Issue by zonca** [zonca/jupyterlab_shellcommand_monitor#1]
I would like the window to automatically refresh every minute. suggestions on how to implement this?

**Comment by jasongrout** [comment]
You could have the frontend jlab extension poll the backend once a second with setTimeout (or setInterval). That way, if the tab is not displayed, you could reduce frequency or turn off polling.

**Comment by zonca** [comment]
Thanks! Is standard typescript enough or there is anything Jupyterlab
specific?

>
