### ISSUE TITLE
Get input from user

### ISSUE THREAD

**Issue by zonca** [zonca/jupyterlab_shellcommand_monitor#2]
I want to display a text form and get input from the user on which command we should execute.

It would be nice also to have a dropdown menu to choose the refresh rate.

**Comment by zonca** [comment]
@jasongrout in https://github.com/zonca/jupyterlab_shellcommand_monitor/blob/master/src/index.ts#L41 I can initialize the content of the widget.
Instead I'd like to make it dynamic. Have the widget display 1 text box to choose the command and 1 slider to choose the refresh rate. Then just below automatically run the requested command at that refresh rate.

Do you have some hints on how to implement that?

**Comment by zonca** [comment]
@jasongrout if you do not have time can you please suggest other ways to get help in developing a JupyterLab extension? I don't have the experience to do it myself. Thanks!

**Comment by jasongrout** [comment]
I'd suggest getting on the gitter channel at https://gitter.im/jupyterlab/jupyterlab, reading through the docs (like the xkcd tutorial at http://jupyterlab.readthedocs.io/en/stable/developer/xkcd_extension_tutorial.html), and posting issues to the jupyterlab repo.
